import { getToken } from '../util/auth'
import { getCreditMenu, getMenu, getLotteryId, getTypeList } from '../util/menu'
import { getSelectAmountData } from '../util/user'

const getters = {
  userInfo: state => state.user.userInfo,
  isLogin: state => state.user.isLogin,
  token: state => state.user.token || getToken() || '',
  lang: state => state.common.lang,
  playTypeList: state => state.menu.playTypeList || getTypeList(),
  showMenuList: state => state.menu.showMenuList,
  menu: state => state.menu.menu || getMenu() || null,
  creditMenu: state => state.menu.creditMenu || getCreditMenu() || null,
  szcpMenuList: state => state.menu.szcpMenuList,
  lotteryId: state => state.game.lotteryId || getLotteryId() || '',
  availablePrizeGroups: state => state.game.availablePrizeGroups,
  isChoiceShow: state => state.game.isChoiceShow,
  shoppingCarList: state => state.game.shoppingCarList,
  showYlPlay: state => state.game.showYlPlay,
  showLrPlay: state => state.game.showLrPlay,
  sscSelectedCounts: state => state.ssc.selectedCounts,
  sscAwardInfo: state => state.ssc.awardInfo,
  sscLastWnNumber: state => state.ssc.lastWnNumber,
  recentWnNumberList: state => state.game.recentWnNumberList,
  defaultSetting: state => state.game.defaultSetting,
  isChasingShow: state => state.menu.isChasingShow,
  isCreateNumber: state => state.menu.isCreateNumber,
  oftenPlayTypes: state => state.game.oftenPlayTypes,
  gameDetail: state => state.game.gameDetail,
  bettingRecordShow: state => state.common.nowShowTab,
  recordTableDataList: state => state.common.recordTableDataList,
  rankingDataShow: state => state.common.rankingDataShow,
  handicapQuickAmount: state => state.common.handicapQuickAmount,
  handicapChoiceWay: state => state.common.handicapChoiceWay,
  quickSelectAmountData: state => state.common.quickSelectAmountData || getSelectAmountData(),
  pk10ShowStatus: state => state.game.pk10ShowStatus,
  isGettingData: state => state.common.isGettingData,
  handicapChoiceBonus: state => state.common.handicapChoiceBonus,
  accountInfo: state => state.user.accountInfo,
  clearFlag: state => state.ssc.clearFlag,
  lotteryNumberLastImInfo: state => state.game.lotteryNumberLastImInfo,
  isImShowBox: state => state.game.isImShowBox,
  imLastShowHeight: state => state.game.imLastShowHeight,
  imGameIsOpening: state => state.game.imGameIsOpening,
  imNowGameTypeName: state => state.game.imNowGameTypeName,
  imNowOpenCounts: state => state.game.imNowOpenCounts,
  prizeVoicePath: state => state.game.prizeVoicePath,
  stopVoiceEnd: state => state.game.stopVoiceEnd,
  stopVoiceEndTwo: state => state.game.stopVoiceEndTwo,
  customerServiceInfo: state => state.common.customerServiceInfo,
  getBonusGroupInGame: state => state.game.getBonusGroupInGame,
  getMultipleInGame: state => state.game.getMultipleInGame,
  getCoefficientInGame: state => state.game.getCoefficientInGame,
  isFirstEnter: state => state.common.isFirstEnter,
  nowScreenStatus: state => state.common.nowScreenStatus
}

export default getters
